export const FETCH_REPO_LIST_LOADING = "FETCH_REPO_LIST_LOADING";
export const FETCH_REPO_LIST_FINISH = "FETCH_REPO_LIST_FINISH";
export const FETCH_REPO_COMMITS_LOADING = "FETCH_REPO_COMMITS_LOADING";
export const FETCH_REPO_COMMITS_FINISH = "FETCH_REPO_COMMITS_FINISH";
